# syntax=docker/dockerfile:1

# Base stage
FROM node:20.11.0-alpine

WORKDIR /email-reset

# Copia apenas o arquivo package.json e package-lock.json
COPY ["package*.json","./"]

# Instala as dependências
RUN npm run build

# Copia todo o restante dos arquivos
COPY . .

# Expor a porta que a aplicação utiliza
EXPOSE 3000

# Executa a aplicação
CMD ["npm", "start"]
