version: '3.8'

services:
  backend: #Backend
    build:
      context: .
      dockerfile: src/backend/Dockerfile.backend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3333:3333"
    command: npm run runNodemon
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=reset_email
    depends_on:
      - db

  frontend: #Frontend
    build:
      context: .
      dockerfile: src/frontend/Dockerfile.frontend
    ports:
      - "3000:3000"

  db: #Banco de dados
    image: mysql:8.0
    hostname: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: reset_email
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p1234"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  db_data: