version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile.backend
    volumes:
      - .:/app
      - /app/node_modules  # Ignore node_modules do host
    ports:
      - "3333:3333"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=reset_email
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: src/frontend/Dockerfile.frontend
    ports:
      - "3000:3000"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: reset_email
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: